# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml

    - name: Set up Nexus
      uses: actions/setup-java@v3
      with: # running setup-java again overwrites the settings.xml
        distribution: 'zulu'
        java-version: '11'
        server-id: mi-nexus-releases # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: NEXUS_USERNAME # env variable for username in deploy
        server-password: NEXUS_PASSWORD # env variable for token in deploy

    - name: Publish to Nexus
      run: ./mvnw deploy
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_KEY }}
